<?php

namespace Container1N393Iy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAcmeApi_Event_JwtCreatedListenerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'acme_api.event.jwt_created_listener' shared autowired service.
     *
     * @return \App\Events\JwtCreatedSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['acme_api.event.jwt_created_listener'] = new \App\Events\JwtCreatedSubscriber(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
    }
}
