<?php

namespace Container1N393Iy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProprieteUserSubscriberService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Events\ProprieteUserSubscriber' shared autowired service.
     *
     * @return \App\Events\ProprieteUserSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Events\\ProprieteUserSubscriber'] = new \App\Events\ProprieteUserSubscriber(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
