<?php

namespace Container1N393Iy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProprieteRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ProprieteRepository' shared autowired service.
     *
     * @return \App\Repository\ProprieteRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ProprieteRepository'] = new \App\Repository\ProprieteRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
