<?php

namespace ContainerXWkxg1K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProprieteUserSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Events\ProprieteUserSubscriber' shared autowired service.
     *
     * @return \App\Events\ProprieteUserSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Events'.\DIRECTORY_SEPARATOR.'ProprieteUserSubscriber.php';

        return $container->privates['App\\Events\\ProprieteUserSubscriber'] = new \App\Events\ProprieteUserSubscriber(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
