<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXWkxg1K\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXWkxg1K/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXWkxg1K.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXWkxg1K\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXWkxg1K\App_KernelDevDebugContainer([
    'container.build_hash' => 'XWkxg1K',
    'container.build_id' => '3788db3a',
    'container.build_time' => 1622074941,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXWkxg1K');
