<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Package extends \App\Entity\Package implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Package' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Package' . "\0" . 'nomPackage', '' . "\0" . 'App\\Entity\\Package' . "\0" . 'prixPackage', '' . "\0" . 'App\\Entity\\Package' . "\0" . 'dateExpiration', '' . "\0" . 'App\\Entity\\Package' . "\0" . 'nbrPropriete', '' . "\0" . 'App\\Entity\\Package' . "\0" . 'nbVedetProp', '' . "\0" . 'App\\Entity\\Package' . "\0" . 'desProp', '' . "\0" . 'App\\Entity\\Package' . "\0" . 'etat', '' . "\0" . 'App\\Entity\\Package' . "\0" . 'typePackage'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Package' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Package' . "\0" . 'nomPackage', '' . "\0" . 'App\\Entity\\Package' . "\0" . 'prixPackage', '' . "\0" . 'App\\Entity\\Package' . "\0" . 'dateExpiration', '' . "\0" . 'App\\Entity\\Package' . "\0" . 'nbrPropriete', '' . "\0" . 'App\\Entity\\Package' . "\0" . 'nbVedetProp', '' . "\0" . 'App\\Entity\\Package' . "\0" . 'desProp', '' . "\0" . 'App\\Entity\\Package' . "\0" . 'etat', '' . "\0" . 'App\\Entity\\Package' . "\0" . 'typePackage'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Package $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomPackage(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomPackage', []);

        return parent::getNomPackage();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomPackage(string $nomPackage): \App\Entity\Package
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomPackage', [$nomPackage]);

        return parent::setNomPackage($nomPackage);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixPackage(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixPackage', []);

        return parent::getPrixPackage();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixPackage(float $prixPackage): \App\Entity\Package
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixPackage', [$prixPackage]);

        return parent::setPrixPackage($prixPackage);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateExpiration(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateExpiration', []);

        return parent::getDateExpiration();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateExpiration(\DateTimeInterface $dateExpiration): \App\Entity\Package
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateExpiration', [$dateExpiration]);

        return parent::setDateExpiration($dateExpiration);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbrPropriete(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbrPropriete', []);

        return parent::getNbrPropriete();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbrPropriete(int $nbrPropriete): \App\Entity\Package
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbrPropriete', [$nbrPropriete]);

        return parent::setNbrPropriete($nbrPropriete);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbVedetProp(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbVedetProp', []);

        return parent::getNbVedetProp();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbVedetProp(int $nbVedetProp): \App\Entity\Package
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbVedetProp', [$nbVedetProp]);

        return parent::setNbVedetProp($nbVedetProp);
    }

    /**
     * {@inheritDoc}
     */
    public function getDesProp(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDesProp', []);

        return parent::getDesProp();
    }

    /**
     * {@inheritDoc}
     */
    public function setDesProp(string $desProp): \App\Entity\Package
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDesProp', [$desProp]);

        return parent::setDesProp($desProp);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', []);

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat(bool $etat): \App\Entity\Package
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', [$etat]);

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypePackage(): ?\App\Entity\TypePackage
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypePackage', []);

        return parent::getTypePackage();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypePackage(?\App\Entity\TypePackage $typePackage): \App\Entity\Package
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypePackage', [$typePackage]);

        return parent::setTypePackage($typePackage);
    }

}
